### ISSUE TITLE
Configuration of signal reading

### ISSUE THREAD

**Issue by BernardinD** [zahidul3/athan-clock#1]
Did you get this to run? I'm not understanding your configurations for the sampling functions. Each function that to sample X/Y sets the other's "minus" as input when I would expect the respective function's "plus" would be set as the input.

While following your setup I'm only able to get some kind of response when I flip the memory registers assigned to the inputs pins

**Comment by zahidul3** [comment]
Hi, can you paste the code snippet that you are referring to? Yes, I am able to run this code.

**Comment by BernardinD** [comment]
@zahidul3 Hi. Never mind, it misunderstood the kind of touchscreen this was. I've gotten it to work now
